runtime: nodejs16 # or another supported version

service: default

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

instance_class: F1

env_variables:
  CI: false 
  REACT_APP_API_KEY: AIzaSyB7V6cD5bMf8FJhZ__I_s7q-U9jHm9bFGY
  REACT_APP_AUTH_DOMAIN: superchat2-61170.firebaseapp.com
  REACT_APP_PROJECT_ID: superchat2-61170
  REACT_APP_STORAGE_BUCKET: superchat2-61170.appspot.com
  REACT_APP_MESSAGING_SENDER_ID: 438362869460
  REACT_APP_APP_ID: 1:438362869460:web:fc6e9fca6c327d0480b541
